### ISSUE TITLE
support "reference" images 

### ISSUE THREAD

**Issue by LATBauerdick** [tomduck/pandoc-fignos#14]
Thanks for this useful tool!  Would it be possible to also support "reference"-type images:

> ![Caption here.][figure-1]{#fig:f1}
> 
> [figure-1]: figures/f1.png

This currently does not work.

I need that because I'm now using Ulysses to edit my markdown for pandoc -- and Ulysses changes the img to become "referenced" instead of "direct". 

Best regards, LatB

**Comment by tomduck** [comment]
Thanks for this feedback, @LATBauerdick.  I agree that pandoc-fignos should support reference-type images.  Let me work it up and get back to you.

**Comment by tomduck** [comment]
It turns out that attributed reference links are already supported for pandoc >= 1.16, but the syntax is different from what you are using. Pandoc 1.16 introduced the following syntax for [link attributes](http://pandoc.org/README.html#extension-link_attributes):

```
![Caption here.][figure-1]

[figure-1]: figures/f1.png {#fig:f1}
```

Does this work for you?

In my regression tests this does not work for pandoc 1.15, and so I have some work to do to fix that.  I will also make a note about attributed reference links in the pandoc-fignos documentation.

**Comment by tomduck** [comment]
I now have this working for pandoc 1.15, and pushed pandoc-fignos 0.12 out to pypi as a result.

**Comment by LATBauerdick** [comment]
great, this works, thank you!

Best regards, LatB

**Comment by tomduck** [comment]
Excellent news!  Thanks again for the feedback.
