### ISSUE TITLE
pandoc-fignos, Rstudio, R markdown, and word output

### ISSUE THREAD

**Issue by HJAllen** [tomduck/pandoc-fignos#2]
Thanks a lot for the effort on this!  This is about the last tool I need to be able to confine workflow to Rstudio and markdown.  I am trying to use pandoc-fignos and the citeproc functionality in the same document.  It seems the two are not behaving well together.  I have added the citeproc info into the header of the demo.md and converted to .Rmd as seen below and added the .bib and .csl files to the demo directory.  The demo.Rmd compiles the fig refs correctly without the csl and bibliography entry but not when they are used.  Any thoughts?
Thanks,

```

---
output:
  word_document: 
    pandoc_args:
    - --filter
    - pandoc-word-newpage
    - --filter
    - pandoc-fignos
  html_document:
    pandoc_args:
    - --filter
    - pandoc-word-newpage
    - --filter
    - pandoc-fignos
csl: environmental-toxicology-and-chemistry.csl
bibliography: HAB.bib

---

Today's data are shown in Fig. @fig:today, and yesterday's data are shown in Fig. @fig:yesterday.

![Today's $y=mx+b$ data.](img/today.png) {#fig:today}

![Yesterday's $y=mx+b$ data.](img/yesterday.png) {#fig:yesterday}

Earlier data are shown in Fig. @fig:earlier.  Fig. {@fig:earlier}a is for two days ago and Fig. {@fig:earlier}b is for three days ago.

![Data from a) two days ago, and b) three days ago.](img/earlier.png) {#fig:earlier .wideimg}

Figures {@fig:today}--{@fig:earlier} (@fig:today,@fig:yesterday,@fig:earlier) reveal an increasing slope with time.


```

**Comment by tomduck** [comment]
Thanks for your feedback, @HJAllen.  Much appreciated.

I haven't used Rstudio, so I may need some more info from you.  But in testing against this issue I did discover some problems:

1) Complex yaml headers were causing a crash.  The problem is now fixed and updated sources have been pushed to github.  Please let me know if this solves your problem.

2) The `--filter pandoc-citeproc` or `--bibliography=FILE` options with pandoc must come _after_ the pandoc-fignos filter call.  I have added this information to the documentation.

For reference, here is the markdown file that I used for testing:

``` .markdown
---
references:
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'http://dx.doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3
...

Today's data are shown in Fig. @fig:today. 

![Today's $y=mx+b$ data.](img/today.png) {#fig:today}

Here is a random reference to @fenner2012a.

References
----------
```

... and here is the command-line call that I used to process it:

``` .bash
pandoc test.md --from=markdown+yaml_metadata_block --filter pandoc-fignos --filter pandoc-citeproc -o test.pdf
```

**Comment by tomduck** [comment]
@HJAllen: Is this issue resolved?  Thanks.

**Comment by HJAllen** [comment]
yes thanks!

**Comment by tomduck** [comment]
Excellent!  Thanks again for your feedback.  Cheers.
