### ISSUE TITLE
Broken file encodings in utf-8

### ISSUE THREAD

**Issue by dbobak** [tomduck/pandoc-fignos#4]
When using option --filter pandoc-fignos, the encoding of utf-8 file gets broken (the national characters are messed).

Below is sample code of source markdown file:

---

title: Tytuł
author:  Dariusz Bobak
date: 2015
csl: c:\Users\deni\zotero\archeo\styles\harvard-polish-archaeology.csl
bibliography: c:\users\deni\documents\archeo\library.bib
...
# Początek

Here you can see problems with polish national characters: zażółć gęślą jaźń
Lorem ipsum dolor sit amet, „consectetur adipiscing «elit». Maecenas at nisi ut sem imperdiet” malesuada. Sed sit amet dolor in ligula commodo accumsan nec et justo. Nunc et velit id libero venenatis vehicula. Pellentesque malesuada bibendum fringilla. Nunc pharetra ut metus (@fig:wykres) vitae semper (\autoref{fig:wykres}). Proin interdum, risus malesuada luctus fermentum, erat arcu tempus tellus, sed dictum quam magna sed quam. Vivamus accumsan id lectus a hendrerit. Etiam nibh turpis, molestie eget dapibus [@bisson_nineteenth_2000] ac, vestibulum nec risus.

![Wykres klimatyczny, w którym pokazujemy mnóstwo ciekawych rzeczy. Na przykład, jak zmieniał się klimat bardzo dawno temu.](fig/wykres.png) {#fig:wykres}

Donec elementum dolor [@adams_bukk_2009] urna, in rhoncus sapien eleifend vitae. Donec dignissim lacus at tellus convallis, sit amet consectetur metus tristique. Donec nec odio ultrices, varius dui sit amet, sodales mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent libero enim, bibendum eu odio imperdiet, finibus pharetra felis. Proin ut blandit est, in accumsan odio. Sed dolor quam, varius non massa vitae, volutpat maximus erat. Etiam lacinia vulputate est a sodales. Aenean nec volutpat leo. Nullam scelerisque turpis eget suscipit varius. Donec mi tortor, sollicitudin sed ligula id, hendrerit imperdiet lectus. Quisque ac tortor quis ligula imperdiet suscipit a sit amet sem. Aliquam erat volutpat.
## Podrozdział pierwszego poziomu

Sed pretium sit amet magna eu tempor. Ut sagittis est et turpis fringilla, a ultrices ex lacinia. Vestibulum leo est, lacinia at egestas a, dignissim maximus velit. Integer nisl neque, fermentum eget congue ac, pulvinar a mauris. Praesent dolor nisi, semper non tortor eu, lobortis mattis nibh. Maecenas rhoncus lorem vel dapibus semper. Praesent vel dolor non velit aliquam scelerisque. Cras quis tincidunt lorem, ac consectetur sapien. Aliquam euismod justo sed leo fringilla pellentesque. Nunc accumsan ut lorem a aliquet.

**Comment by kenduck** [comment]
For @tomduck : Thanks. Away and will see to on Monday.

**Comment by tomduck** [comment]
Thanks for your feedback, @dbobak.  Sorry for the delay.  I have been away on travel.

I can't seem to reproduce the error.  I reduced your text to this minimal example:

```
Polish national characters: zażółć gęślą jaźń. 

Below is Fig. @fig:one.

![Polish national characters: zażółć gęślą jaźń.](fig.png) {#fig:one}
```

I processed it with the following command:

```
pandoc test.md --filter pandoc-fignos -o test.pdf
```

The output looks good to me.  Could you please give this a try?

It would also be helpful to know what version of pandoc, python and pandoc-fignos you are using.  I am using pandoc 1.14.0.1, python 2.7.6 and pandoc-fignos 0.2.2.

**Comment by dbobak** [comment]
@tomduck, sorry for a late response, I have been on travel also :)
The problem still exist with your sample, you can find output and input files here:
https://dl.dropboxusercontent.com/u/1111886/fignos-test.zip

When processing the file without using fignos, with command:

```
pandoc test.md -o test_no_fignos.pdf
```

the output is correct.

I am using:
Python version 3.4.3
Pandoc version 1.14.0.1
Fignos version 0.2.2

**Comment by tomduck** [comment]
Thanks, @dbobak.  The only obvious difference is in our python versions.  I copied `pandoc_fignos.py` into the test directory and ran the following in bash:

```
pandoc test.md -t json | python3.4 pandoc_fignos.py | pandoc -f json -o test.pdf
```

This allows me to control the python version used when running pandoc_fignos.py.  I obtained correct results for both python 2.7 and 3 on two different OS's: Mac OS X and Debian linux.

So, a few questions:
1. What OS are you using?
2. Can you run similar tests to mine above with whatever python versions you have?  I would be interested to know if the problem you see is isolated to python3 on your machine.
3. Are you having problems with other output formats or just pdf?

Cheers.

**Comment by dbobak** [comment]
@tomduck, the OS I'm using is Windows 8.1 (64bit), polish version. I have similiar configuration (as mentioned in earlier post) on three machines and on each of the the problem exists. It also appears with other formats (I've checked docx and html).

Anyway, I have installed Python 2.7 and followed the way you have suggested. And the results are correct. So it looks like it is a problem of Python 3 on Windows.

**Comment by tomduck** [comment]
@dbobak: Success! ...of a sort.  I have reproduced your error on a Windows 7.1 system.  :o)

**Comment by dbobak** [comment]
@tomduck: Sort of great ;) That means the problem is not with my installations.

**Comment by tomduck** [comment]
@dbobak: I have pushed some commits to github.  Could you please install pandoc-fignos from source to see if the changes solve your problem?  I will push out a new version to pypi once we have agreed that the bug is fixed.

Note: This works with Windows Console.  Powershell appears to mess with the encoding when using pipelines (as described a few posts earlier).

---

Here is the situation as I understand it (documented here for future reference).

From the [pandoc documentation](http://pandoc.org/README.html):

> Pandoc uses the UTF-8 character encoding for both input and output.

Pandoc-fignos must therefore do the same.  In both python 2 and 3, a call to `sys.stdin.read()` returns a string.  The catch is that strings are different kinds of objects between the two python versions.

[Python 2 strings](https://docs.python.org/2.7/reference/lexical_analysis.html#strings) are represented by a series of bytes (ASCII characters).  Any decoding is left to the programmer.  Since pandoc-fignos mostly passes bytes through to `sys.stdout` there is no ill effect on any platform.

[Python 3 strings](https://docs.python.org/3/reference/lexical_analysis.html#strings), on the other hand, are unicode, and so decoding is performed automatically.  The [default expectations](https://docs.python.org/3.5/library/sys.html) for encoding depend on the OS:

> The character encoding is platform-dependent. Under Windows, if the stream is interactive (that is, if its isatty() method returns True), the console codepage is used, otherwise the ANSI code page. Under other platforms, the locale encoding is used (see locale.getpreferredencoding()).

UTF-8 is the default encoding of most locales for [many linux distributions](https://www.cl.cam.ac.uk/~mgk25/unicode.html#linux) and [Mac OS X](https://en.wikipedia.org/wiki/Mac_OS_Roman#Application_notes).  This is why pandoc-fignos worked with those OSes.  On Windows with python 3 the default encoding is something else, hence we need to enforce pandoc's requirement.  Stackoverflow shows [how to do this](https://stackoverflow.com/questions/16549332/python-3-how-to-specify-stdin-encoding).

One final note: The change between python 2 and 3 addressed a variety of problems (viz., ["the change is for the better"](https://docs.python.org/3/whatsnew/3.0.html)).  What we have here appears to be an edge case where things were made a little more difficult in python 3.

**Comment by dbobak** [comment]
@tomduck I have installed pandoc-fignos with the following command:

```
pip install git+https://github.com/tomduck/pandoc-fignos.git
```

It upgraded successfully, then I've run:

```
pandoc test.md --filter pandoc-fignos -o test.pdf
```

and

```
pandoc test.md --filter pandoc-fignos -o test.docx
```

Both of them produced correct results, so it looks that the bug is fixed. All the files (just for checking) are there:
https://dl.dropboxusercontent.com/u/1111886/fignos-test2.zip

**Comment by tomduck** [comment]
_Fantastic_.  Thanks for your help, @dbobak.

I had to make one little change: the handling for python 2 is now left as is.  Everything is tested and seems to work on my end.  I have pushed version 0.3 to pypi.

If you have any further trouble with it, please let me know.

Cheers.  :o)
