### ISSUE TITLE
Attributes processing bug

### ISSUE THREAD

**Issue by HaoZeke** [tomduck/pandoc-fignos#41]
Pandoc 2 supports image parameters to be passed as:

```markdown
![Caption](blah.png "Alt"){width=50%}
![Caption](blah.png "Alt"){width=50%}{#fig:iBreak}
![Caption](blah.png "Alt"){width=50%, #fig:iBreakToo}
![Caption](blah.png "Alt"){#fig:iWork}
```
Apart from the last one the middle two break..

**Comment by tomduck** [comment]
Hi there.  Thanks for your feedback.

I can't find the behaviour you describe documented anywhere in the pandoc manual or release notes.  I ran a test of your code to see how pandoc would process it alone without the pandoc-fignos filter.  It doesn't appear that the syntax you describe is supported by pandoc.

Can you please clarify?  Perhaps there is something I am not understanding.

**Comment by HaoZeke** [comment]
This is new to `pandoc-2` I believe, it's documented [here](https://pandoc.org/MANUAL.html#images) under link_attributes ..

**Comment by tomduck** [comment]
Thanks, @HaoZeke.  Link and image attributes have actually been in place since [pandoc 1.16](http://pandoc.org/releases.html#pandoc-1.16-02-jan-2016).

According to the pandoc manual, [attributes](http://pandoc.org/MANUAL.html#extension-link_attributes) should be in a *space-separated* list (no commas) in a *single* set of curly braces.  I have tested your code with pandoc alone (no pandoc-fignos) and it is ignoring the faulty syntax in your #iBreak and #iBreakToo examples.

However, I see that pandoc-fignos is raising its own exception for the #iBreak example.  That shouldn't be happening and I will fix it.  The faulty syntax should be ignored as is done by pandoc.

Note that [figures must be in their own paragraph](http://pandoc.org/MANUAL.html#extension-implicit_figures), otherwise they are treated as inline images.  Just put a blank line in between each figure.

Cheers,
Tom

**Comment by tomduck** [comment]
I fixed the bug in the `nextrelease` branch, and will push it out in a new release within the next week.  Thanks again for reporting this Issue.
