### ISSUE TITLE
Fatal error with pandoc 2.0 if id contains slash

### ISSUE THREAD

**Issue by dnebauer** [tomduck/pandoc-fignos#43]
According to the pandoc-fignos [github page](https://github.com/tomduck/pandoc-fignos) label ids can contain "letters, numbers, dashes, slashes and underscores." If I include a slash ('/'), however, pandoc gives me the error:

```sh
$ pandoc --filter pandoc-fignos -t html eq-slash.md
Error running filter pandoc-fignos:
Error in $.blocks[1].c[0].c[0]: cannot unpack array of length 7 into a tuple of length 3
```

Test file `eq-slash.md`:
```md
See figure @fig:my/image.

![My image](image.jpg "My image"){#fig:my/image}
```

Pandoc version: 2.0.5 (Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.5).
Pandoc-fignos version: 0.21.1.

Removing the slash from the figure ids stops the error occurring and pandoc generates correct output successfully.

Both pandoc-eqnos and pandoc-tablenos are able to successfully handle equation and table ids with slashes; this problem is occurring only with pandoc-fignos.

**Comment by tomduck** [comment]
Thanks for your feedback, @dnebauer.

I just released version 1.0.0 today, and I think that should eliminate the "fatal" error.  I believe this problem was fixed in the 1.0.0 pre-releases.

However, it would appear that pandoc itself does not accept slashes in ids.  Pandoc does its own figure attribute processing.  If you turn off pandoc-fignos, you will notice that ids with slashes do not get processed.  I have adjusted the documentation accordingly.
