### ISSUE TITLE
Unsure how to handle an error

### ISSUE THREAD

**Issue by ericmjl** [tomduck/pandoc-fignos#77]
@tomduck first off, want to thank you for making the xnos series of packages. It's been a great help in developing a workflow for writing papers in Markdown.

I have an issue where using the fignos filter gives me the following error at the terminal, for which I was hoping you might be able to offer some guidance on where to debug:

```
    %%%% pandoc-fignos: required package
    \usepackage{caption}

    %% pandoc-fignos: environment to disable figure caption prefixes
    \makeatletter
    \newcounter{figno}
    \newenvironment{fignos:no-prefix-figure-caption}{
      \caption@ifcompatibility{}{
        \let\oldthefigure\thefigure
        \let\oldtheHfigure\theHfigure
        \renewcommand{\thefigure}{figno:\thefigno}
        \renewcommand{\theHfigure}{figno:\thefigno}
        \stepcounter{figno}
        \captionsetup{labelformat=empty}
      }
    }{
      \caption@ifcompatibility{}{
        \captionsetup{labelformat=default}
        \let\thefigure\oldthefigure
        \let\theHfigure\oldtheHfigure
        \addtocounter{figure}{-1}
      }
    }
    \makeatother
```

I'm wondering if there might be something that I am missing here? (I admittedly haven't used LaTeX much, so I'm not sure whether I might be doing something wrong though.)

**Comment by tomduck** [comment]
Hello and sorry for the long wait.  This actually isn't an error message.  There should be a little more text above what you posted that says: 

```
pandoc-fignos: Wrote the following blocks to header-includes.  If you
use pandoc's --include-in-header option then you will need to manually
include these yourself.
```

So, this is just pandoc-fignos letting you know what it is doing.  This info is given because of a major change that was made with the 2.0 release.  I wanted to make sure that nobody was caught by surprise.

If you would like to hide these warning messages, then you can reduce the `fignos-warning-level` as per the documentation.

Cheers,
Tom
